name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TAG_NAME: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabi gcc-mipsel-linux-gnu u-boot-tools lzop

      - name: u-boot-hi3516av100
        run: |
          git clone https://github.com/openipc/u-boot-hi3516av100.git --depth 1
          cd u-boot-hi3516av100
          git apply ../patches/u-boot-hi3516av100.patch
          cp -f ../scripts/u-boot-hi3516av100.sh build.sh
          bash build.sh

      - name: u-boot-hi3516cv100
        run: |
          git clone https://github.com/openipc/u-boot-hi3516cv100.git --depth 1
          cd u-boot-hi3516cv100
          git apply ../patches/u-boot-hi3516cv100.patch
          cp -f ../scripts/u-boot-hi3516cv100.sh build.sh
          bash build.sh

      - name: u-boot-hi3516cv200
        run: |
          git clone https://github.com/openipc/u-boot-hi3516cv200.git --depth 1
          cd u-boot-hi3516cv200
          git apply ../patches/u-boot-hi3516cv200.patch
          cp -f ../scripts/u-boot-hi3516cv200.sh build.sh
          bash build.sh

      - name: u-boot-hi3516cv300
        run: |
          git clone https://github.com/openipc/u-boot-hi3516cv300.git --depth 1
          cd u-boot-hi3516cv300
          git apply ../patches/u-boot-hi3516cv300.patch
          cp -f ../scripts/u-boot-hi3516cv300.sh build.sh
          bash build.sh

      - name: u-boot-hi3516cv500
        run: |
          git clone https://github.com/openipc/u-boot-hi3516cv500.git --depth 1
          cd u-boot-hi3516cv500
          cp -f ../scripts/u-boot-hi3516cv500.sh build.sh
          bash build.sh

      - name: u-boot-hi3516ev200
        run: |
          git clone https://github.com/openipc/u-boot-hi3516ev200.git --depth 1
          cd u-boot-hi3516ev200
          cp -f ../scripts/u-boot-hi3516ev200.sh build.sh
          bash build.sh

      - name: u-boot-ingenic
        run: |
          git clone https://github.com/openipc/u-boot-ingenic.git --depth 1
          cd u-boot-ingenic
          bash build.sh

      - name: u-boot-sigmastar
        run: |
          git clone https://github.com/openipc/u-boot-sigmastar.git --depth 1
          cd u-boot-sigmastar
          bash build.sh

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TAG_NAME}}
          files: |
            u-boot-hi3516av100/output/u-boot-hi3516av100-universal.bin
            u-boot-hi3516av100/output/u-boot-hi3516dv100-universal.bin
            u-boot-hi3516cv100/output/u-boot-hi3516cv100-universal.bin
            u-boot-hi3516cv100/output/u-boot-hi3518cv100-universal.bin
            u-boot-hi3516cv100/output/u-boot-hi3518ev100-universal.bin
            u-boot-hi3516cv200/output/u-boot-hi3516cv200-universal.bin
            u-boot-hi3516cv200/output/u-boot-hi3518ev200-universal.bin
            u-boot-hi3516cv300/output/u-boot-hi3516cv300-universal.bin
            u-boot-hi3516cv300/output/u-boot-hi3516ev100-universal.bin
            u-boot-hi3516cv500/output/u-boot-hi3516av300-universal.bin
            u-boot-hi3516cv500/output/u-boot-hi3516cv500-universal.bin
            u-boot-hi3516cv500/output/u-boot-hi3516dv300-universal.bin
            u-boot-hi3516ev200/output/u-boot-hi3516ev200-universal.bin
            u-boot-hi3516ev200/output/u-boot-hi3516ev300-universal.bin
            u-boot-hi3516ev200/output/u-boot-hi3518ev300-universal.bin
            u-boot-ingenic/output/u-boot-t10-nor.bin
            u-boot-ingenic/output/u-boot-t10l-nor.bin
            u-boot-ingenic/output/u-boot-t20-nor.bin
            u-boot-ingenic/output/u-boot-t20l-nor.bin
            u-boot-ingenic/output/u-boot-t20x-nor.bin
            u-boot-ingenic/output/u-boot-t21n-nor.bin
            u-boot-ingenic/output/u-boot-t30a-nor.bin
            u-boot-ingenic/output/u-boot-t30a1-nor.bin
            u-boot-ingenic/output/u-boot-t30l-nor.bin
            u-boot-ingenic/output/u-boot-t30n-nor.bin
            u-boot-ingenic/output/u-boot-t30x-nor.bin
            u-boot-ingenic/output/u-boot-t31a-nor.bin
            u-boot-ingenic/output/u-boot-t31al-nor.bin
            u-boot-ingenic/output/u-boot-t31l-nor.bin
            u-boot-ingenic/output/u-boot-t31lc-nor.bin
            u-boot-ingenic/output/u-boot-t31n-nor.bin
            u-boot-ingenic/output/u-boot-t31x-nor.bin
            u-boot-sigmastar/output/u-boot-ssc30kd-nor.bin
            u-boot-sigmastar/output/u-boot-ssc30kq-nor.bin
            u-boot-sigmastar/output/u-boot-ssc325-nor.bin
            u-boot-sigmastar/output/u-boot-ssc325de-nand.bin
            u-boot-sigmastar/output/u-boot-ssc333-nor.bin
            u-boot-sigmastar/output/u-boot-ssc335de-nor.bin
            u-boot-sigmastar/output/u-boot-ssc335-nor.bin
            u-boot-sigmastar/output/u-boot-ssc337de-nor.bin
            u-boot-sigmastar/output/u-boot-ssc337de-nand.bin
            u-boot-sigmastar/output/u-boot-ssc337-nor.bin
            u-boot-sigmastar/output/u-boot-ssc338q-nand.bin
            u-boot-sigmastar/output/u-boot-ssc338q-nor.bin
            u-boot-sigmastar/output/u-boot-ssc338q-ram.bin
            u-boot-sigmastar/output/u-boot-ssc377-nor.bin
